on: workflow_dispatch

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/454682782912/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'github-service-account@hanzhenyi-test-308600.iam.gserviceaccount.com'
      - uses: actions/checkout@v2
        with:
          repository: yihanzhen/artifact-registry-npm-tools
          ref: skip-scope-check
          path: ./artifact-registry-npm-tools
      - run: ./artifact-registry-npm-tools/src/main.js
      - run: npm publish