on: workflow_dispatch

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm test
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/hanzhenyi-test-308600/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'github-service-account@hanzhenyi-test-308600.iam.gserviceaccount.com'
      - run: npx artifact-registry-auth
      - run: npm publish